stages:
  - test
  - build

cache:
  key: "v1"
  paths:
    - node_modules/

before_script:
  - apk update
  - apk add --no-cache build-base
  - apk add --no-cache python-dev
  - apk add --no-cache libffi-dev
  - apk add --no-cache libressl-dev
  - apk add --no-cache py-pip
  - apk add --no-cache make
  - pip install docker-compose

test:
  stage: test
  script:
    - make test

build-prod:
  stage: build
  script:
    - make build
  only:
    - master
